dist: trusty
sudo: required

language: cpp

compiler:
  - g++

branches:
  only:
  - development
  - master
  - "/feature.*/"
  - "/hotfix.*/"

addons:
  apt:
    packages:
      - python3.6
      - cmake
    sources: &sources
      - deadsnakes
      - ubuntu-toolchain-r-test

install: 
  # C++14
  - sudo apt-get install -qq gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script:
  - cp .travis.buildOptions.txt buildOptions.txt
  - ls
  - python3.6 --version
  - g++ --version
  - python3.6 pythonTools/mbuild.py -g make
  - make -j4
