name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - development
      - 'feature*'
      - 'hotfix*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Get latest CMake
        uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - if: startsWith(matrix.os, 'windows')
        name: run on windows
        run: |
          tools/setup.cmd
          mbuild.exe
      #- if: startsWith(matrix.os, 'macOS')
      #  name: run on mac
      #  run: |
      #    sh tools/setup.cmd
      #    ./mbuild gen make
      #    cd build
      #    make
      - if: startsWith(matrix.os, 'ubuntu')
        name: run on linux
        run: |
          sh tools/setup.cmd
          ./mbuild gen make
          cd build
          make
